name: gitartwork from a contribution graph
on: 
  push:
  pull_request:
  schedule:
    - cron: '* */24 * * *'
  workflow_dispatch:  
jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ChrispaixK/gitartwork@v1
        with:
           user_name: ChrispaixK
           text: CHRISPAIXK
      - uses: ChrispaixK/simple-push-action@v1
